server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: app_user
    password: secret
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      idle-timeout: 60000
      max-lifetime: 100000
      keepalive-time: 30000
      validation-timeout: 5000
      connection-timeout: 15000
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/springboot-test
          jwk-set-uri: http://localhost:8081/realms/springboot-test/protocol/openid-connect/certs
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:

        spring.json.trusted.packages: com.example.chat.dto
        spring.json.value.default.type: com.example.chat.dto.ChatEvent
        spring.json.use.type.headers: false

    bootstrap-servers: localhost:9092

    admin:
      fail-fast: true